### ISSUE TITLE
Preserve the prototype when setting in an object

### ISSUE THREAD

**Issue by chrisbouchard** [kube/monolite#12]
It would be good if `set` preserved the prototype, so that it can be used with instances of classes with methods.

**Comment by chrisbouchard** [comment]
I'm working on a merge request right now. I have to figure out how to tag this issue.

**Comment by kube** [comment]
Do you have an example use case for this?

I'm not really convinced by keeping prototypes on objects handled my Monolite, but I could change my mind if you show a concrete use-case for this.

**Comment by chrisbouchard** [comment]
Here is the use case I have in mind:

```typescript
class Person {
    constructor(public firstName: string, public lastName: string) {}
    fullName(): string { return `${firstName} ${lastName}`; }
}

const person1 = new Person('Adam', 'West');
const person2 = set(person1, _ => _.lastName)('Savage');

person1.fullName();  // 'Adam West'
person2.fullName();  // Should be 'Adam Savage', but currently will cause an error
```

**Comment by chrisbouchard** [comment]
Also, it just seems right that `x instanceof y` if and only if `set(x, f)(a) instanceof y`, which requires that the prototype be preserved.

**Comment by nahuel** [comment]
Note, `lodash/fp` `set` preserves the proto correctly:
```js
m = require('monolite')
f = require('lodash/fp')

class C { constructor() { this.a = 1}}
var obj = new C()

m.set(obj, _ => _.a)(3)  // { a: 3 }
f.set(['a'], 3, obj)     // C { a: 3 }
```
I think monolite must also preserve the proto, is the more useful, well-typed and unsurprising behavior.

**Comment by kube** [comment]
Ok, Nominal Typing convinced me.

I will add support for prototype tomorrow. (Your PR cannot be merged as I changed a lot of things in Monolite since, and in particular passed from Mocha to Jest)
