### ISSUE TITLE
Add RegEx-based getAccessorChain to support ES5

### ISSUE THREAD

**Issue by kube** [kube/monolite#17]

**Comment by spacejack** [comment]
Just FYI, one of my use cases is like:

    set(arr, _ => _[index].foo)("abc")

Not sure how I'd write a regex to handle that.

**Comment by kube** [comment]
Yes, this is something I already have in mind.

I was working on something based on `eval()` to access the current scope (In this case the `index` variable).

But as the call to `eval()` will be in the scope of the library, there's no way to access the calling scope which contains `index`.

I think I'm gonna drop this idea, and just work on the Babel plugin, (which should be able to convert `_ => _[index].foo` to `[index, 'foo']`, as it will directly transform the AST.

I leave this issue open, just in case I find a solution, and if you find any solution please let me know.

**Comment by spacejack** [comment]
Ok, thaks for the effort :)
