### ISSUE TITLE
Flow types not type validating correctly

### ISSUE THREAD

**Issue by petegleeson** [kube/monolite#19]
Hello, I am trying to use this library with Flow. I am finding that the flow types included in this library are not validating the way I would expect. See the following examples:

``` js
// @flow
import { set } from 'monolite';

type State = {
    id: number,
    username: string,
};

const state: State = {
    id: 1,
    username: 'foo',
};

const stateWithStringId = set(state, s => s.id)('hello');

const stateWithNumberUsername = set(state, s => s.username)(1);

const stateWithNewKey = set(state, s => s.whatever)('hello');
```

I would expect an error on each of these usages of `set`. When I run flow, however, I see no errors.

```
➜  monolite-spike node_modules/flow-bin/cli.js version
Flow, a static type checker for JavaScript, version 0.51.1
➜  monolite-spike node_modules/flow-bin/cli.js index.js        
No errors!
```

Has anyone had success using monolite and flow together? What version of flow does flowgen use? Maybe some more recent flow language features have fixed this.

**Comment by kube** [comment]
Hi,
Sorry for taking this time to answer.
I will investigate this tonight.

**Comment by kube** [comment]
I just removed the automatic Flow types generation using Flowgen, as it caused problems with some of its dependencies when using Yarn.

So Monolite does not provide anymore Flow types, for now at least.
