### ISSUE TITLE
Missing null guard in deepEqual

### ISSUE THREAD

**Issue by jeremejevs** [kube/monolite#21]
`objectEqual` throws when passed a `null`. That, in turn, can happen because, [unfortunately](https://archive.is/sPyGA), `typeof null === 'object'`, so none of the preceding checks in `deepEqual` are able to filter it out. A `typeof` wrapper could probably suffice (returning `'null'` for `x === null`, and `typeof x` otherwise).

**Comment by kube** [comment]
Thanks for the report!
This deepEqual function needs rework, I will take a look tomorrow.

**Comment by jeremejevs** [comment]
Thank you!

**Comment by jeremejevs** [comment]
Can you cut a release, please?

**Comment by kube** [comment]
Yes sorry totally forgot. I do that at noon.

**Comment by kube** [comment]
Released on NPM.

**Comment by jeremejevs** [comment]
Thanks!
