### ISSUE TITLE
Allow chained calls

### ISSUE THREAD

**Issue by eldamir** [kube/monolite#8]
Rather than having to do

```es6
const newState = set(set(oldState, _ => _.foo)('bar'), _ => _.bob)('Alice')
```

or

```es6
let newState = set(oldState, _ => _.foo)('bar')
newState = set(newState, _ => _.bob)('Alice')
```

it would be cool if calls could be chained like 

```es6
const newState = S(oldState)
                             .set(_ => _.foo)('bar')
                             .set(_ => _.bob)('Alice')
```

or better yet

```es6
const newState = S(oldState)
                             .set(_ => _.foo, 'bar')
                             .set(_ => _.bob, 'Alice')
```

**Comment by kube** [comment]
Yeah in fact I was hoping that the [Pipeline Operator](https://github.com/mindeavor/es-pipeline-operator) would be here soon, and that would permit to do it like this:

```ts
state
  |> set(_ => _.foo, 'bar')
  |> set(_ => _.bob, 'Alice')
```

Anyway, we can't wait for this to be accepted by TC39 and implemented in TypeScript.

### There are multiple way to do this

We can wrap the state with a function that will add the set method and enable Fluent-Style.

The issue here is that the `set` method could **shadow** a `set` property of the state:
```ts
const state = {
  set: 42   // This won't be accessible anymore if a set method exists
}
```

So we would need to **unwrap** the state before returning, which is not really sexy:
```ts
wrap(state)
  .set(_ => _.foo, 'bar')
  .set(_ => _.bob, 'Alice')
  .unwrap()
```

This would also mean that we're not doing anymore Functional but doing Object-Oriented programming.

***

Another way would be to do function composition:
```ts
compose(
  state => set(state, _ => _.foo, 'bar'),
  state => set(state, _ => _.foo, 'bar')
)
```
But maybe it would add too much verbosity.

***

Last idea would be to function that takes multiple setProperty:

```ts
compose(state)(
  setProperty(_ => _.foo)('bar'),
  setProperty(_ => _.foo)('bar')
)
```
This one would need to export two functions from the library.

***

Of course the names of the functions are only to illustrate and wouldn't have this name in the implementation.

I'm still not sure about the way to go, did not find the perfect way, and maybe there are some better ways and syntax, feel free to comment and make a proposal.

Last thing, the issue with the multiple currying of the `set` function (`set(root, accessor)(value)`)  is to make TypeScript type inference work. I'm currently working on ways to provide more simple syntax.

**Comment by kube** [comment]
I still have no solution about this, but I currently format my code in a way that makes the code more readable:

```ts
set(set(state,
  _ => _.statements)(action.payload),
  _ => _.currentStatement)(0)
```

**Comment by epeli** [comment]
I would prefer to use `compose()` with a data last function. This would be breaking change of course but it would align nicely with lodash/fp and Ramda.

I've used lodash/fp like this in vanilla JS:

```js
import {update, compose} from "lodash/fp"

var s1 = {
  foo: {
    bar: 0
  }
}

var s2 = compose(
  update(["foo", "bar"], n => n + 1),
  update(["foo", "bar"], n => n * 2),
)(s1)
````

So monolite should have api  like this:

```typescript
var s2 = compose(
    monolite.set(_ => _.foo.bar, n => n + 1),
    monolite.set(_ => _.foo.bar, n => n * 2),
)(s1)
```

which desugars to

```typescript
var s2 = s1;
s2 = monolite.set(_ => _.foo.bar, n => n + 1)(s2);
s2 = monolite.set(_ => _.foo.bar, n => n * 2)(s2);

```

The compose function is totally generic here. The compose from lodash should be usable with monolite too.

**Comment by kube** [comment]
@epeli Here the issue would be on type inference.
Accessor function completion and static checks are permitted thanks to the fact that it's preceded by the root argument.

So it's expressed like this:
```ts
function set <R, T>(root: R, accessor: (root: R) => T)
```

This would not be possible anymore on a curried function, as `set(_ => _.foo.bar)` would not be bound to any root object type.

Pipeline Operator would solve this problem, as the root object would be passed implicitly.

**Comment by jeremejevs** [comment]
> Last thing, the currying of the `set` function (`set(root, accessor)(value)`) is to make TypeScript type inference work.

Could you elaborate, please? Is this about forcing TS to infer the `T` from `set`'s `accessor`? That is, a workaround for [this unfortunate limitation](https://github.com/Microsoft/TypeScript/issues/6627)? Or something else?

> I'm currently working on ways to provide more simple syntax.

Do you have something particular in mind?

**Comment by kube** [comment]
@jeremejevs The linked TypeScript issue is not relevant for this particular problem.

An expression can not be typed from a type passed AFTER expression definition.
(You can not define a function type from a future call to it, as this same function could be called with different argument types)

One of the solutions I have in mind would be to add a `pipe` function in Monolite to permit to achieve a pipeline like this:

```ts
pipe(state)(
  $ => set($, _ => _.foo)('bar'),
  $ => set($, _ => _.baz)('bar')
)
```

I think I'm gonna add that in the next release, it has the benefit of being generic enough to be used for multiple things, and permitting to resolve the input type of the first function in the pipeline. (And thus permit type inference)

This will solve this problem at the cost of a little more verbosity, until the real game-changer, the Pipeline Operator comes to Stage 3 and is added to TypeScript.

**Comment by jeremejevs** [comment]
Well, the linked issue isn't 1-to-1 to Monolite's case (which would be `set(root, accessor, value)`, I presume), but I think it's the same problem. But that isn't important, just wanted to understand the source of the limitation, and you have provided an explanation, thanks.

The `pipe` looks good, but I don't think it needs currying? Here's what I'm currently using:

```ts
import { flow } from 'lodash'

export const pipe = <S>(state: S, ...setters: ((state: S) => S)[]): S =>
  flow(setters)(state)
```

Not a conventional pipe, but `pipe(state)(setters)` isn't either.

**Comment by kube** [comment]
Really late, but better than never. :)

Just reworked the library using Conditional Types and `infer` in #33.
You now can do chained transformations on an object:

```ts
import { pipe } from 'monolite'

const updatedState =
  pipe(state)
    .set(_ => _.nested.counter, x => x + 1)
    .set(_ => _.nested.message, word => word + '!')
    .end()
```

> Note: This update breaks backward compatibility as `set` is not curried anymore, and some functions were removed, should not be hard to update though (simply remove currying).

**Comment by kube** [comment]
I'm currently reusing this library so gonna update it with better Static Typing, and clean the api.

I think that instead of exposing a `pipe` function I will just provide the `set` function:

```ts
// Fluent-style API if only passing root
const updatedState = set(state)
  .set(_ => _.nested.counter, x => x + 1)
  .set(_ => _.nested.message, word => word + '!')
  .end()
```

```ts
// Classic behaviour if everything is passed
const updatedState = set(state, _ => _.nested.counter, x => x + 1)
```

This would prevent possible collision with a `pipe` function from a function library.

It would also allow to provide shortcuts directly as methods:

```ts
set(state)
  .set(_ => _.nested.name, "Hello!")
  .map(_ => _.nested.collection, item => set(item, _ => _.price, x => x * 2))
  .end();

// And `map` could even take multiple accessors
// (the first ones should return an array)
// in case of nested properties inside collection
set(state)
  .map(_ => _.nested.collection, _ => _.price, x => x * 2)
  .end();

set(state)
  .map(
    _ => _.nested.collection,
    _ => _.nestedInEachCollection.items,
    _ => _.price,
    x => x * 2
  )
  .end();
```

Open to feedback on the idea.

**Comment by jeremejevs** [comment]
I agree that `pipe` isn't the best name, but I'm not sure if it's a good idea to overload `set`. Though yeah, a novelty nickname could be even more confusing. Either way, I'd consider some more options. Maybe something with a `start` in it, since there's also an `end`?

**Comment by kube** [comment]
I'm gonna release a version with the spec just described above, along with an update with the Babel plugin. (and update the README)

Though, it does mean this is the definitive API, I'm still open to discussion on it, I'm willing to make Monolite evolve to be as easy as it can be to use, and with the best performance possible.

So do not hesitate to do a proposition for an evolution on this API.
The thing is that IMO exposing too much functions is not a good idea, what I would like is to have only `set` and a future `get` exposed from `monolite`.

**Comment by kube** [comment]
I close this issue as chained calls were added as overload of `set` in https://github.com/kube/monolite/pull/36.

But do not hesitate to create a discussion in a new issue about the Monolite api.
